--
-- The Archetype is configured with "hibernate.hbm2ddl.auto" value="create-drop" in "persistence.xml".
--
-- This will cause hibernate to populate the database when the application is started by processing the files that
-- were configured in the hibernate.hbm2ddl.import_files property.
--
-- This file is responsible for initializing table sequences.   The numbers here need
-- to be greater than the ids that are inserted as part of load_catalog_data.sql (or other load files)
-- to prevent duplicate key exceptions.
--

--
-- Initialize SEQUENCE_GENERATOR values
--
INSERT INTO SEQUENCE_GENERATOR VALUES ('OrderImpl',2);
INSERT INTO SEQUENCE_GENERATOR VALUES ('OrderItemImpl',9);
INSERT INTO SEQUENCE_GENERATOR VALUES ('FulfillmentGroupImpl',3);
INSERT INTO SEQUENCE_GENERATOR VALUES ('AddressImpl',3);
INSERT INTO SEQUENCE_GENERATOR VALUES ('PhoneImpl',1);
INSERT INTO SEQUENCE_GENERATOR VALUES ('FulfillmentGroupItemImpl',1);
INSERT INTO SEQUENCE_GENERATOR VALUES ('PersonalMessageImpl',1);
INSERT INTO SEQUENCE_GENERATOR VALUES ('RatingSummaryImpl',10);
INSERT INTO SEQUENCE_GENERATOR VALUES ('RatingDetailImpl',10);
INSERT INTO SEQUENCE_GENERATOR VALUES ('ReviewDetailImpl',10);
INSERT INTO SEQUENCE_GENERATOR VALUES ('MediaImpl',100000);
INSERT INTO SEQUENCE_GENERATOR VALUES ('CategoryImpl',10000);
INSERT INTO SEQUENCE_GENERATOR VALUES ('ProductImpl',1000);
INSERT INTO SEQUENCE_GENERATOR VALUES ('CodeTypeImpl',100);
INSERT INTO SEQUENCE_GENERATOR VALUES ('OfferImpl',500);
INSERT INTO SEQUENCE_GENERATOR VALUES ('OfferItemCriteriaImpl', 10);
INSERT INTO SEQUENCE_GENERATOR VALUES ('OfferCodeImpl',10);
INSERT INTO SEQUENCE_GENERATOR VALUES ('CategoryProductImpl',500);
INSERT INTO SEQUENCE_GENERATOR VALUES ('SearchInterceptImpl',1);
INSERT INTO SEQUENCE_GENERATOR VALUES ('SkuImpl',10000);
INSERT INTO SEQUENCE_GENERATOR VALUES ('FeaturedProductImpl',100);
INSERT INTO SEQUENCE_GENERATOR VALUES ('CrossSaleProductImpl',5);
INSERT INTO SEQUENCE_GENERATOR VALUES ('UpSaleProductImpl',5);
INSERT INTO SEQUENCE_GENERATOR VALUES ('PageImpl', 1000);
INSERT INTO SEQUENCE_GENERATOR VALUES ('FieldGroupImpl', 1000);
INSERT INTO SEQUENCE_GENERATOR VALUES ('FieldDefinitionImpl', 1000);
INSERT INTO SEQUENCE_GENERATOR VALUES ('PageFieldImpl', 1000);
INSERT INTO SEQUENCE_GENERATOR VALUES ('FieldEnumerationImpl', 1000);
INSERT INTO SEQUENCE_GENERATOR VALUES ('FieldEnumerationItemImpl', 1000);
INSERT INTO SEQUENCE_GENERATOR VALUES ('StructuredContentImpl', 1000);
INSERT INTO SEQUENCE_GENERATOR VALUES ('StructuredContentFieldImpl', 1000);
INSERT INTO SEQUENCE_GENERATOR VALUES ('StructuredContentRuleImpl',1000);
INSERT INTO SEQUENCE_GENERATOR VALUES ('SandBoxImpl', 100);
INSERT INTO SEQUENCE_GENERATOR VALUES ('AdminUserImpl',100);
INSERT INTO SEQUENCE_GENERATOR VALUES ('AdminRoleImpl',100);
INSERT INTO SEQUENCE_GENERATOR VALUES ('AdminPermissionImpl',100);
INSERT INTO SEQUENCE_GENERATOR VALUES ('ProductAttributeImpl',1000);
INSERT INTO SEQUENCE_GENERATOR VALUES ('URLHandlerImpl',100);
INSERT INTO SEQUENCE_GENERATOR VALUES ('CategorySearchFacetImpl',100);
INSERT INTO SEQUENCE_GENERATOR VALUES ('CategoryExcludedSearchFacetImpl',100);
INSERT INTO SEQUENCE_GENERATOR VALUES ('SearchFacetImpl',100);
INSERT INTO SEQUENCE_GENERATOR VALUES ('FieldImpl',100);
INSERT INTO SEQUENCE_GENERATOR VALUES ('SearchFacetRangeImpl',100);
INSERT INTO SEQUENCE_GENERATOR VALUES ('ProductOptionImpl', 100);
INSERT INTO SEQUENCE_GENERATOR VALUES ('ProductOptionValueImpl', 100);

