-- Menus
INSERT INTO BLC_CMS_MENU (MENU_ID, NAME) VALUES (1, 'Header Nav');

-- Menu Items
INSERT INTO BLC_CMS_MENU_ITEM (MENU_ITEM_ID, PARENT_MENU_ID, SEQUENCE, MENU_ITEM_TYPE, CATEGORY_ID, LABEL) VALUES (1, 1, 1, 'CATEGORY', 2001, 'Home');
INSERT INTO BLC_CMS_MENU_ITEM (MENU_ITEM_ID, PARENT_MENU_ID, SEQUENCE, MENU_ITEM_TYPE, CATEGORY_ID, LABEL) VALUES (2, 1, 2, 'CATEGORY', 2002, 'Hot Sauces');
INSERT INTO BLC_CMS_MENU_ITEM (MENU_ITEM_ID, PARENT_MENU_ID, SEQUENCE, MENU_ITEM_TYPE, CATEGORY_ID, LABEL) VALUES (3, 1, 3, 'CATEGORY', 2003, 'Merchandise');
INSERT INTO BLC_CMS_MENU_ITEM (MENU_ITEM_ID, PARENT_MENU_ID, SEQUENCE, MENU_ITEM_TYPE, CATEGORY_ID, LABEL) VALUES (4, 1, 4, 'CATEGORY', 2004, 'Clearance');
INSERT INTO BLC_CMS_MENU_ITEM (MENU_ITEM_ID, PARENT_MENU_ID, SEQUENCE, MENU_ITEM_TYPE, LINKED_PAGE_ID, LABEL) VALUES (5, 1, 5, 'PAGE', 3, 'New to Hot Sauce?');
INSERT INTO BLC_CMS_MENU_ITEM (MENU_ITEM_ID, PARENT_MENU_ID, SEQUENCE, MENU_ITEM_TYPE, LINKED_PAGE_ID, LABEL) VALUES (6, 1, 6, 'PAGE', 2, 'FAQ');
